# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://github.com/LivePersonInc/iOSPodSpecs.git' #LiveEngage Pod Repository

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LPMessagingSDK'
  # Pods for SampleApp

end